<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [9]:
#assert condition-to-check, output
x= 5-6
assert x>=0, 'DUMMY'


AssertionError: DUMMY

### 1.2 try-except

In [2]:
number=input("Give me a number and I will calculate it's square")
square=int(number)**2
print(f'The square of {number} is {square}')

Give me a number and I will calculate it's square2
The square of 2 is 4


In [5]:
try:
    number=input("Give me a number and I will calculate it's square")
    square=int(number)**2
    print(f'The square of {number} is {square}')
except:                                                    #if the input for number does not fulfil the criteria to become an integer
    print(f"Oh no! I can't print the square of {number}")

Give me a number and I will calculate it's squarehaha
Oh no! I can't print the square of haha


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [13]:
def funny_add(a, b, c=2):            #by making c=1, the original input for C will always be c=1 , unless an additional input is provided, which replaces c=1 by c=new value.
    return a + 10*b+ 100**c
funny_add(2, 4, 3)

1000042

### 2.2 Docstrings

In [1]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how
    positional, keyword and default arguments
    work.
    '''
    return a+ 10*b + 100*c
help(funny_add)


Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how
    positional, keyword and default arguments
    work.



### 2.3 Function are first class citizens

In [20]:
def my_function(angle, trig_function):
    return trig_function(angle)

x=my_function(np.pi/2, np.sin)
print(x)

y=my_function(np.pi/2, np.cos)
print(y)

z=my_function(np.pi/2, lambda x:np.cos(2*x))
print(z)

1.0
6.123233995736766e-17
-1.0


### 2.4 More unpacking

In [3]:
x, y, z = [1, 2, 3]
print(x, y, z)

x, y, z = np.array([1, 2, 3])
print(z, y, x)

x, *_, z = np.array([1, 2, 3, 4, 5])
print(x,z)



1 2 3
3 2 1
1 5


## Exercise 1 :  A better calculator I

In [76]:
def add(x, y):
    return x+y

def subtract(x, y):
    return x-y

def multiply(x, y):
    return x*y

def divide(x, y):
    return x/y
    assert any(y== 0),'You cant divide by 0'

x=np.array([36, 32, 44, 76, 27])
y=np.array([64, 46, 9, 24, 73])

subtract(x, y)
divide(x, y)

array([0.5625    , 0.69565217, 4.88888889, 3.16666667, 0.36986301])

In [137]:
x=np.array([36, 32, 44, 76, 27])
y=np.array([0, 46, 9, 24, 73])

def divide(x,y):
    z = 0 in y
    print(z)
    assert z != True, "you can't divide by 0!"
    return(x/y)

divide(x, y)

True


AssertionError: you can't divide by 0!

## Exercise 2 :  A better calculator II

In [7]:
np.seterr(all='raise')

x=np.array([36, 32, 44, 76, 27])
y=np.array([2, 46, 9, 24, 73])

def add(x, y):
    return x+y

def subtract(x, y):
    return x-y

def multiply(x, y):
    return x*y

def divide(x, y):
    return x/y

try: 
    divide(x, y)
    print(divide(x, y))
except:
    print(">>>>")

divide(x, y)

[18.          0.69565217  4.88888889  3.16666667  0.36986301]


array([18.        ,  0.69565217,  4.88888889,  3.16666667,  0.36986301])

In [19]:
x=np.array([36, 32, 44, 76, 27])
y=np.array([0, 46, 9, 24, 73])
solved_arr =[]



try:
    a = x/y
    solved_arr.append(a)
    assert any(y != 0), "y = 0"
except:
    solved_arr.append('this operation is undefined')
            
print(solved_arr)

[array([       inf, 0.69565217, 4.88888889, 3.16666667, 0.36986301])]


/var/folders/s7/krzz8k4n5tq00twfqgws3fcm0000gn/T/ipykernel_42203/4250014244.py:8: RuntimeWarning: divide by zero encountered in divide
  a = x/y


In [27]:
def divide(x,y):
    try:
        x/y
        assert any(y!=0)
    except:
        np.nan
x/y

/var/folders/s7/krzz8k4n5tq00twfqgws3fcm0000gn/T/ipykernel_42203/1870858195.py:7: RuntimeWarning: divide by zero encountered in divide
  x/y


array([       inf, 0.69565217, 4.88888889, 3.16666667, 0.36986301])