<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [6]:
#print() is also considered a python function

def greeting(name):
    if name == 'Batman':
        return "Hello Batman, it's good to see you"
    else:
        return f'Hello {name}'

greeting('aqua')


'Hello aqua'

In [7]:
import numpy as np


def basic_stats(numbers):
    np_numbers = np.array(numbers)
    return np_numbers.max(), np_numbers.min(), np_numbers.mean()

### 1.2 Named functions that don’t return

### 1.3 Anonymous functions

In [17]:
my_short_function = lambda name: f"Hello {name}!"
my_short_function(name='viper')

'Hello viper!'

In [25]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         #Sort by comparing the default key 
                                        # (i.e. the 1st element) 
    
sorted(numbers, key=lambda x:x[0])

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

### 1.4 Optional arguments

In [28]:
def greeting(name = 'No one'):
    if name == 'Batman':
        print(f'Hello {name}! So nice to meet you!')
    else:
        print(f'Hello {name}!')
greeting('Batman')

Hello Batman! So nice to meet you!


In [29]:
?print

In [30]:
print('I', 'am', 'Batman', sep='___')

I___am___Batman


## 2 The importance of functions?

### 2.1 An argument for functions

Abstraction of a function
- condensing something highly complex with numerous moving parts into something more comprehensible or simply does its job

Ensuring that the code is reusable meaning it can be applied to various scenarios and is simple enough to replicate.

Changes to a function only occur at a few places, and ensures that debugging a code is simpler.


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

The function uses if name == 'Batman'
The usage of a == indicates a True or False output where only if it is True will the desired output be displayed. 




## Exercise 2 :  Calculator functions

In [8]:
import numpy as np
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def add(x,y):
    return(x + y)

def subtract(x,y):
    return (x-y)

def multiply(x, y):
    return(x*y)

def divide(x,y): 
    if any(ele == 0 for ele in y):
        print('You dumbass')
        exit()
    else:
        return(x/y)

print(divide(x,y))
print(add(x, y))
print(subtract(x, y))


[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]
[100 100 100 100 100]
[-28 -32 -12  52 -46]


## Exercise 3 :  max_info() with NumPy

In [3]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
def max_info(numbers):
    result = np.max(numbers), np.argmax(numbers)
    return result
max_info(numbers)



(83, 2)