<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [9]:
import numpy as np
py_super_names= ['Black Widow', 'Iron Man', 'Doctor Strange']
py_real_names= [ 'Natasha Romanoff', 'Tony Stark', 'Stephen Strange']

np_super_names = np.array(['Black Widow', 'Iron Man', 'Doctor Strange'])
np_real_names = np.array([ 'Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

superhero_info = {'Natasha Romanoff': 'Black Widow',
                 'Tony Stark': 'Iron Man',
                 'Stephen Strange': 'Doctor Strange'
                 }


['Natasha Romanoff' 'Tony Stark' 'Stephen Strange']


### 1.2 Accessing data from a list (or array)

In [12]:
#accessing data from a list or array requires the code to know the index of that specific data within the array/list

print(py_super_names[0])
print(np_super_names[-1])

Black Widow
Doctor Strange


### 1.3 Accessing data from a dictionary

In [17]:
#to call information from a dictionary, know the associated key for each value
print(superhero_info['Natasha Romanoff'])

#Keys can be accessed through the use of .keys()
superhero_info.keys()

#similarly, values can also be attained through .values()
superhero_info.values()

Black Widow


dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [18]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

## 2 Lists vs. Arrays

### 2.1 Size

In [24]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
        
len(py_list_2d)
len(np_array_2d)

np_array_2d.shape
np_array_2d.size

20

### 2.2 Arrays are fussy about type

In [25]:
#only tolerate a single type of data, be it string, integers, floats, all the data becomes standardised.

py_list=[1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [28]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array + 10        #adds 10 to every value within the list

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [31]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 12, 14, 16, 18]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

print(py_list_1 + py_list_2)    #puts all the values within 2 lists together
print(np_array_1 + np_array_2)  #Addition of the each corresponding index value


[1, 2, 3, 4, 5, 10, 12, 14, 16, 18]
[11 14 17 20 23]


### 2.5 Multiplying by a Number

In [34]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

py_list * 2              #makes 2 sets of the list into 1 list
np_array * 2             #multiplies each value within the list by 2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [43]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

#py_list**2 doesnt work because the list, but you could use a for loop
[i**2 for i in py_list]
np.square(np_array)

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [48]:
py_list = [1, 2, 3, 4, 5]

py_list == 1   #asks the question if the variable attached to py_list is equal to 1


False

In [61]:
np_array = np.array(py_list)
np_array >= 3

array([False, False,  True,  True,  True])

### 2.8 Mathematics

In [72]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

sum(py_list)    #sums all values within the list
max(py_list)    # finds the greatest value within the list
min(py_list)    # finds the lowest value within the list

np_array.sum()
np_array.mean()
np_array.min()

1

## Exercise 1 :  Total recall?

A list and array comprises of similar styles of data, where the order or index of each value matters in relation to one another
Mathematical functions can be employed on lists and arrays. 

A list can be treated as a set of values within a specific variable and is commonly treated as a whole. In comparison, the array can be viewed as a matrix of values where each individual value would be taken into consideration when executing an operation.

When multiplying a list, the function *2 would result in the overall list being multiplied such as [1, 1, 1] becoming [1, 1, 1, 1, 1, 1]. However, in an array, it would take the individual elements and multiply by 2 to return an array of the same size, such as [2, 2, 2] for an initial array of [1, 1, 1]

A dictionary is a form of information storage that contains 2 different sets of information, the first being a key and the second being the corresponding value to the key. 



## Exercise 2 :  Index me

In [6]:
import re
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'

def py_list2(n):
    result = []
    for i in n:
        if (int(i[1]))%2 != 0:
            result.append(i)
    return result
py_list2(py_list)

a1
c3
e5
g7
i9


['a1', 'c3', 'e5', 'g7', 'i9', 'j10']

## Exercise 3 :  Capitalise Heros

In [94]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
                 
for x in superhero_info:
    superhero_info[x] = superhero_info[x].upper()
superhero_info['Natasha Romanoff']



'BLACK WIDOW'

## Exercise 4 :  How many ones

In [128]:
import numpy as np
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]
n = np.array(numbers)
sum(n == 1)

9