<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [6]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = np_array
x[0:4]
x[0:8:2]
x[5:]

array(['f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

### 1.2 Subsetting by masking (Arrays only)

In [36]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array >3
print(my_mask)
np_array[my_mask]
print(np_array[~(np_array > 3)])                         # '~' means 'NOT'
print(np_array[(np_array > 3) & (np_array < 8)])         # '&' means 'AND'
print(np_array[(np_array < 3) | (np_array > 8)])         # '|' means 'OR'

print(np_array>5)

[False False False  True  True  True  True  True  True  True]
[1 2 3]
[4 5 6 7]
[ 1  2  9 10]
[False False False False False  True  True  True  True  True]


### 1.3 Indexing & Slicing 2D Lists

In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[3]

[4, 'D']

In [16]:
py_list_2d[3][0]

4

In [15]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

### 1.4 Indexing & Slicing 2D Arrays

In [ ]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])


### 1.5 Growing lists

In [18]:
x = 1*[10]
x

x2= [1]
x2 = x2 + [2]
x2= x2 + [3]
x2

x3=[1]
x3+=[2]
x3+=[4]

x3

#appending multiple elements into the same list at one shot
x = [1]
x+=[2, 3, 4, 5]  #appends it to the back of the list
x

x = [1]
x= [2, 3, 4, 4, 5] + x #pre-pends the elements to the back of the front of the list
x

#.apppend() funciton being used to append the element directly instead of rewriting too many lines of cofe
x = []
x.append(1, 2, 3) #does not work as .append takes only 1 argument
x

TypeError: list.append() takes exactly one argument (3 given)

## 2 Some loose ends

### 2.1 Tuples

In [28]:
#tuples are lists created using () instead of [] and cannot be changed after creation

a=(1, 2, 3)

# to access the data, use the print function, referencing the tuple and the desired element's index
print(a[:2])
print(a[1:])
print(a[0:])

#trying to append a new element to the list will not work
a[0] = [0]

(1, 2)
(2, 3)
(1, 2, 3)


TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [ ]:
x = [1, 2, 3, 4]

#DO NOT USE ANOTHER VARIABLE TO REFERNCE X TO COPY THE LIST FROM X AS IT WILL CHANGE X FOR A CHANGE IN THE NEW VARIABLE
y=x
z=x

#use the .copy() function instead
y=x.copy()
z = x.copy()


## Exercise 1 :  Total recall?

Subsetting : refers to getting only the specified element within a specified list

Indexing: Refers to the numerical positioning of the element within a list , where the index of the first element is 0, followed by 1 and so on.

Slicing: Literally means to slice out the segment of a list, such as taking reference to all elements after a specific index in [2:] or anything before the index of [:1]. However, the index 1 referenced in [:1] will not be shown. 

*Masking 


## Exercise 2 :  Show me the ‘odd’ letters

In [88]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

array = np_array_2d[0:, 0]
print(array)
x = array.astype(int)     #makes the string into integers
y = x%2
z = (y != 0)
z

array2 = np_array_2d[0:, 1]
array2

result = []
for ind in range(len(z)):
    if (z[ind]):
        result.append(array2[ind])

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']


In [89]:
result

['A', 'C', 'E', 'G', 'I']